---
- name: Include common preflight tasks
  include_tasks: "common/preflight.yml"

- name: perform common installation procedure
  include_tasks: "common/install.yml"

- name: Include OS and distribution specific installation tasks.
  include_tasks: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution|lower }}/install.yml"
        - "{{ ansible_os_family|lower }}/install.yml"
      skip: true
  tags:
    - install

- name: Include common configuration tasks
  include_tasks: "common/config.yml"

- name: Include common launch tasks
  include_tasks: "common/launch.yml"
