---
- name: Restart Grafana service
  become: true
  service:
    name: "{{ _service_name }}"
    state: restarted
  listen: Restart service

- name: Stop Grafana systemd service
  become: true
  service:
    name: "{{ _service_name }}"
    state: stopped
    enabled: false
  listen: Uninstall service

- name: Remove Grafana systemd service file
  become: true
  file:
    path: "/etc/systemd/system/grafana.service"
    state: absent
  listen: Uninstall service

- name: Remove Grafana install dir
  become: true
  file:
    path: "{{ install_dir }}"
    state: absent
  listen: Uninstall service
  when: install_type == "archive"

- name: Remove Grafana config dir
  become: true
  file:
    path: "{{ config_dir }}"
    state: absent
  listen: Uninstall service

- name: Remove Grafana config dir
  become: true
  file:
    path: "{{ config_dir }}"
    state: absent
  listen: Uninstall service

- name: Remove Grafana data dir
  become: true
  file:
    path: "{{ data_dir }}"
    state: absent
  listen: Uninstall service

- name: Remove Grafana provisioning dir
  become: true
  file:
    path: "{{ provisioning_dir }}"
    state: absent
  listen: Uninstall service

- name: Remove Grafana plugins dir
  become: true
  file:
    path: "{{ plugins_dir }}"
    state: absent
  listen: Uninstall service

- name: Remove Grafana user
  become: true
  user:
    name: "{{ grafana_user }}"
    state: absent
    remove: true
  listen: Uninstall service

- name: Remove Grafana group
  become: true
  group:
    name: "{{ grafana_user }}"
    state: absent
  listen: Uninstall service
