---
- name: Ensure existence of config dir
  become: true
  file:
    path: "{{ config_dir }}"
    owner: "{{ grafana_user }}"
    group: "{{ grafana_user }}"
    state: directory

- name: Ensure existence of logs dir
  become: true
  file:
    path: "{{ logs_dir }}"
    owner: "{{ grafana_user }}"
    group: "{{ grafana_user }}"
    state: directory

- name: Ensure existence of data dir
  become: true
  file:
    path: "{{ data_dir }}"
    owner: "{{ grafana_user }}"
    group: "{{ grafana_user }}"
    state: directory

- name: Ensure existence of provisioning dir
  become: true
  file:
    path: "{{ provisioning_dir }}"
    owner: "{{ grafana_user }}"
    group: "{{ grafana_user }}"
    state: directory

- name: Ensure existence of plugins dir
  become: true
  file:
    path: "{{ plugins_dir }}"
    owner: "{{ grafana_user }}"
    group: "{{ grafana_user }}"
    state: directory

- name: Include provisioned configuration tasks
  include_tasks: "common/config/{{ item }}.yml"
  with_items: "{{ provision_configs }}"
  tags:
    - config
