---
- name: Ensure Grafana system group exists
  become: true
  group:
    name: "{{ grafana_user }}"
    state: present
    system: true
  tags:
    - install

- name: Create Grafana system user
  become: true
  user:
    comment: Grafana service account
    name: "{{ grafana_user }}"
    group: "{{ grafana_user }}"
    shell: "/sbin/nologin"
    system: true
    create_home: false
  tags:
    - install

- name: Create installation directory
  file:
    path: "{{ install_dir }}"
    state: directory
    owner: "{{ grafana_user }}"
    group: "{{ grafana_user }}"
  become: true
  when: install_type == "archive"
  tags:
    - install

- name: Download Grafana archive ({{ archive_url }})
  get_url:
    url: "{{ archive_url }}"
    dest: "/tmp/{{ archive_url | urlsplit('path') | basename }}"
    checksum: "{{ checksum_format }}:{{ archive_checksum }}"
    owner: "{{ grafana_user }}"
    group: "{{ grafana_user }}"
    mode: '0775'
  register: archive_tmp
  become: true
  when: install_type == "archive"
  tags:
    - install

- name: Extract Grafana archive
  become: true
  unarchive:
    src: "{{ archive_tmp.dest }}"
    dest: "{{ install_dir }}"
    owner: "{{ grafana_user }}"
    group: "{{ grafana_user }}"
    mode: '0775'
    remote_src: true
    extra_opts:
      - --strip-components
      - '1'
  when: install_type == "archive"
  tags:
    - install
